version: '3.3'

volumes:
  static:
  media:
  docs:


services:

  backend:
    container_name: foodgram-back
    build: ../backend
    env_file: ../backend/.env
    volumes:
      - static:/backend_static
      - media:/media
      - docs:/docs


  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
        - static:/frontend_static
    depends_on:
      - backend

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles
      - media:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

    depends_on:
        - backend
        - frontend